query blog_mdx($relativePath: String!) {
  blog_mdx(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Blog_mdxParts
  }
}

query blog_mdxConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Blog_mdxFilter) {
  blog_mdxConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Blog_mdxParts
      }
    }
  }
}

query blog_md($relativePath: String!) {
  blog_md(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Blog_mdParts
  }
}

query blog_mdConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Blog_mdFilter) {
  blog_mdConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Blog_mdParts
      }
    }
  }
}
